### PR TITLE
(maint) handle Night's Watch

### PR DESCRIPTION
**Pull request by alexandru-d-popa**

### CODE REVIEW

**Comment by gimmyxd** [comment]
A more elegant solution which handles all the cases:
```ruby
require 'highline'

cli = HighLine.new
z = 'Night"s watch'
x = "Night's watch"

>> cli.say("<%= color(%Q[#{z}], BOLD) %>")
Night"s watch
>> cli.say("<%= color(%Q[#{x}], BOLD) %>") 
Night's watch
```

**Review by gimmyxd — CHANGES_REQUESTED** [review]
Also please cleanup the commented pry's

**Review by gimmyxd — CHANGES_REQUESTED** [review]
@loopinu the only thing you need to change is the string handling in the `say` method. I used the `require 'highline'` and the `cli` object just to show that the `%Q` handles both quotes cases.

**Comment by alexandru-d-popa** [comment]
New interpolation works see results below:
----- Git commits in Jira -----
COMMIT TOKENS NOT FOUND IN JIRA (OR NOT WITH FIX VERSION OF puppet-agent 6.8.0)
PA-28**
PE-27***

**Review by gimmyxd — APPROVED** [review]

**Pull request merged**
