### PR TITLE
(SERVER-2415) Expose Team information from ticketmatch

### PR DESCRIPTION
**Pull request by justinstoller**
Previously, we did not expose any team ownership information via
ticketmatch, which left those leading the Puppet release with a long
list of tickets that may or may not be owned by them and little help for
other leads whose teams may have tickets/commits in Puppet.

To aid this we now expose team ownership when listing tickets resolved
w/o commits or commits w/o tickets resolved and allow filtering tickets
listed by a team.

This way a Puppet lead can see immediately what team should be pinged
for incompleted work and other teams can quickly see what work of theirs
is outstanding w/in Puppet.

### CODE REVIEW

**Comment by justinstoller** [comment]
This is a little different approach than what we originally discussed in the retro. 

Originally, I had in mind something that would allow the Server team lead to see, when running ticketmatch from the server repo, to see if there also tickets that might be applicable in PUP. But to get those tickets we'd either need to make those PUP tickets have a SERVER X.X.X version or also input the PUP version, and then to figure out their state you'd still need to switch over to the puppet repo and re-run it.

So I figured this way was better, but I'd love some feedback. I'm thinking with this update we'd up the process so the Agent lead would NOT specify a team when running ticketmatch and then ping teams that still have open unresolved tickets in Puppet. While the Server lead would also be expected to run ticketmatch in the puppet repo but specify the "Server" team to ensure they're work is in the correct states.

**Comment by justinstoller** [comment]
Happy to break this up into multiple commits if folks want.

**Comment by justinstoller** [comment]
Don't know who all I should ping for review but figured I'd start there   (;

**Comment by Magisus** [comment]
Gonna try this out.

**Comment by Magisus** [comment]
So what is the top message supposed to indicate? I see team tags for the unresolved tickets, but none for those with the fix version missing. Is that intentional?
```
----- Git commits in Jira -----
COMMIT TOKENS NOT FOUND IN JIRA (OR NOT WITH FIX VERSION OF SERVER 6.0.3 AND A TEAM OF Server)
CPR-650
DOC-3180
DOC-3822
DOC-3825
DOCUMENT-936
DOCUMENT-951
RE-11577
TK-473

----- Unresolved Jira tickets not in git commits -----
ALL ISSUES WERE FOUND IN GIT

----- Unresolved Jira tickets found in git commits -----
UNRESOLVED ISSUES FOUND IN GIT
SERVER-2399	Resolved               (Server)
SERVER-2416	Ready for CI           (Server)
SERVER-2418	Resolved               (Server)
SERVER-2421	Resolved               (Server)
```

The CPR ticket has "Team: Release Engineering", while for example TK-473 does have Server.

Update: The top section is for tickets that didn't show up in the JIRA query, that do show up in Git. When "team" is specified, this query only includes tickets that are a) in the project b) have the fix version and c) have the specified team. Two updates might make this clearer: The banner should probably say "Git commits NOT in Jira" and the message should be simpler, like "WRONG PROJECT, FIX VERSION, OR TEAM".

**Comment by justinstoller** [comment]
Yeah that threw me for a loop at first too. I think "Git commits in Jira" is misleading, those are git commits that include JIRA keys in their commit message but but tickets matching those keys were not actually returned when searching JIRA (so all we have is the key from a git commit to go on).

**Comment by justinstoller** [comment]
Ping.

I'd love to have one of the agent team reviewers also play with this.

My goal is to have this merged (or a replacement for it if folks don't like the approach) before the next release retro.

**Pull request merged**
